---
  - name: Install nginx
    apt: name=nginx state=latest

  - name: Write nginx.conf
    template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - Restart nginx

  - name: Delete default vhost
    file: path=/etc/nginx/sites-enabled/default state=absent
    notify:
      - Restart nginx

  - name: Add nginx vhosts
    template: src=vhost.j2 dest=/etc/nginx/sites-available/{{ item.name }}
    with_items: vhosts
    notify:
      - Restart nginx

  - name: Link nginx vhosts in sites-enabled
    file: src=/etc/nginx/sites-available/{{ item.name }} dest=/etc/nginx/sites-enabled/{{ item.name }} state=link
    with_items: vhosts
    notify:
      - Restart nginx

