---
  - name: install nginx
    apt: name=nginx state=latest

  - name: write nginx.conf
    template: src=templates/nginx.conf.j2 dest=/etc/nginx/nginx.conf
    notify:
      - restart nginx

  - name: delete default vhost
    file: path=/etc/nginx/sites-enabled/default state=absent
    when: delete_default_vhost
    notify:
      - restart nginx
