---
  - name: install git package
    apt: name=git state=latest

  - name: install build essential package
    apt: name=build-essential state=latest

  - name: install ruby 1.9 package
    apt: name=ruby1.9.1 state=latest

  - name: install ruby 1.9 dev package
    apt: name=ruby1.9.1-dev state=latest

  - name: add nodejs ppa
    apt_repository: repo=ppa:chris-lea/node.js

  - name: install nodejs
    apt: name=nodejs state=latest
