---
- name: Add the deploy user
  user: name=deploy
        home=/home/deploy
        shell=/bin/bash
        comment="Deploy User"

- name: Set up authorized_keys for the deploy user
  authorized_key: user=deploy
                  state=present
                  key="{{ item }}"
  with_file: "{{ ansible_local_path }}/files/public_keys/josef-pospisil"

- name: Remove github.com from deploy's known_hosts
  file: dest=/home/deploy/known_hosts state=absent
  sudo: True
  sudo_user: deploy

- name: Add github.com to deploy's known_hosts
  shell: ssh-keyscan -H github.com > /home/deploy/.ssh/known_hosts
  sudo: True
  sudo_user: deploy

- name: Set up id_rsa key for deploy user
  copy: src="{{ ansible_local_path }}/files/private_keys/id_rsa"
        dest=/home/deploy/.ssh/id_rsa
        owner=deploy
        group=deploy
        mode=0600
